package patterns.builder;

import models.Order;
import models.Customer;
import models.Product;
import java.util.ArrayList;
import java.util.List;

/**
 * OrderBuilder - Builder pattern implementation for Order construction
 * 
 * DESIGN PATTERN: Builder Pattern
 * PURPOSE: Constructs complex Order objects step by step
 * 
 * JUSTIFICATION:
 * - Order objects have many parameters (customer, products, address, payment, type, etc.)
 * - Traditional constructors with many parameters are difficult to use and error-prone
 * - The order of parameters in constructors can be confusing
 * - Some parameters are optional (e.g., special instructions, gift wrapping)
 * - Builder pattern provides a fluent, readable API for constructing orders
 * - Allows constructing orders in any order with clear, named methods
 * - Makes the code more maintainable and less error-prone
 * 
 * BENEFITS:
 * - Fluent interface: order.setCustomer().addProduct().setShipping().build()
 * - Clear and readable code
 * - Flexible construction - can build orders step by step
 * - Validates the order before creating it
 * - Can have default values for optional parameters
 * 
 * USAGE EXAMPLE:
 * Order order = new OrderBuilder()
 *                   .setCustomer(customer)
 *                   .addProduct(product1)
 *                   .addProduct(product2)
 *                   .setShippingAddress(address)
 *                   .setPaymentMethod("Credit Card")
 *                   .setOrderType("Express")
 *                   .build();
 * 
 * @author E-commerce System Team
 */
public class OrderBuilder {
    
    private static int orderCounter = 2000; // Start from 2000 to distinguish from factory orders
    
    // Required parameters
    private String orderId;
    private Customer customer;
    private List<Product> products;
    
    // Optional parameters with default values
    private String shippingAddress;
    private String paymentMethod;
    private String orderType = "Standard"; // Default to Standard order
    private double totalAmount;

    /**
     * Constructor initializes the builder with empty products list
     */
    public OrderBuilder() {
        this.orderId = "ORD" + (orderCounter++);
        this.products = new ArrayList<>();
    }

    /**
     * Sets the customer for the order
     * 
     * @param customer Customer placing the order
     * @return This builder instance for method chaining
     */
    public OrderBuilder setCustomer(Customer customer) {
        this.customer = customer;
        return this;
    }

    /**
     * Adds a single product to the order
     * 
     * @param product Product to add
     * @return This builder instance for method chaining
     */
    public OrderBuilder addProduct(Product product) {
        if (product != null) {
            this.products.add(product);
        }
        return this;
    }

    /**
     * Adds multiple products to the order
     * 
     * @param products List of products to add
     * @return This builder instance for method chaining
     */
    public OrderBuilder addProducts(List<Product> products) {
        if (products != null) {
            this.products.addAll(products);
        }
        return this;
    }

    /**
     * Sets the products list for the order
     * 
     * @param products Complete list of products
     * @return This builder instance for method chaining
     */
    public OrderBuilder setProducts(List<Product> products) {
        this.products = new ArrayList<>(products != null ? products : new ArrayList<>());
        return this;
    }

    /**
     * Sets the shipping address
     * 
     * @param shippingAddress Shipping address
     * @return This builder instance for method chaining
     */
    public OrderBuilder setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
        return this;
    }

    /**
     * Sets the payment method
     * 
     * @param paymentMethod Payment method (e.g., "Credit Card", "PayPal")
     * @return This builder instance for method chaining
     */
    public OrderBuilder setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }

    /**
     * Sets the order type
     * 
     * @param orderType Order type ("Standard" or "Express")
     * @return This builder instance for method chaining
     */
    public OrderBuilder setOrderType(String orderType) {
        this.orderType = orderType;
        return this;
    }

    /**
     * Sets a custom order ID (optional, auto-generated by default)
     * 
     * @param orderId Custom order ID
     * @return This builder instance for method chaining
     */
    public OrderBuilder setOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Calculates the total amount based on products and shipping
     * 
     * @return Total order amount
     */
    private double calculateTotalAmount() {
        double productTotal = products.stream()
                                     .mapToDouble(Product::getPrice)
                                     .sum();
        
        double shippingCost = "Express".equalsIgnoreCase(orderType) ? 25.0 : 10.0;
        
        return productTotal + shippingCost;
    }

    /**
     * Validates that all required fields are set before building
     * 
     * @throws IllegalStateException if required fields are missing
     */
    private void validate() {
        if (customer == null) {
            throw new IllegalStateException("Customer is required to build an order");
        }
        
        if (products == null || products.isEmpty()) {
            throw new IllegalStateException("At least one product is required to build an order");
        }
        
        if (shippingAddress == null || shippingAddress.trim().isEmpty()) {
            throw new IllegalStateException("Shipping address is required to build an order");
        }
        
        if (paymentMethod == null || paymentMethod.trim().isEmpty()) {
            throw new IllegalStateException("Payment method is required to build an order");
        }
    }

    /**
     * Builds and returns the Order object
     * Validates all required fields before construction
     * 
     * @return Constructed Order object
     * @throws IllegalStateException if required fields are missing
     */
    public Order build() {
        validate();
        
        // Calculate total amount
        totalAmount = calculateTotalAmount();
        
        // Create and return the order
        return new Order(orderId, customer, products, shippingAddress, 
                        paymentMethod, orderType, totalAmount);
    }

    /**
     * Resets the builder to initial state
     * Useful for building multiple orders with the same builder
     * 
     * @return This builder instance
     */
    public OrderBuilder reset() {
        this.orderId = "ORD" + (orderCounter++);
        this.customer = null;
        this.products = new ArrayList<>();
        this.shippingAddress = null;
        this.paymentMethod = null;
        this.orderType = "Standard";
        this.totalAmount = 0.0;
        return this;
    }
}
